Переформирована имеющаяся структура проекта
SimplifyPlusPlus/simplify-project pull request #2
Opened 2022-03-29 16:00 UTC by seljmov

2022-03-29 16:43 UTC, iamquoz requested changes

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.API/Controllers/ClientsController.cs
> +            .Select(client => new ClientBaseDto
todo: добавить маппер

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.API/Program.cs
> +	public static void Main(string[] args)
у нас же 6 дотнет...

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +			var url = $"https://localhost:7011{endpoint}";
в appsettings указать урл?

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +		await Console.Error.WriteLineAsync($"Обращение к эндпоинту {endpoint} привело к ошибке -> {e.Message}");
async?

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +			var url = $"https://localhost:7011{endpoint}";
ну и слеш тут оставь-то, зачем передавать каждый раз

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Front/Pages/Clients/Clients.razor
> +            "Произошла ошибки при получении данных о клиентах.");
произошла ошибка
произошли ошибки

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Front/Program.cs
> +		builder.Services.AddScoped(_ => new HttpClient {BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)});
вот же, достаешь baseaddress

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Front/Shared/NavButton.razor
> +    public string? Classes { get; set; }
А есть смысл передавать классы ей?

Давай тут сделаем пресеты и из них выбирать

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Front/wwwroot/css/open-iconic/README.md
> +[Open Iconic v1.1.1](http://useiconic.com/open)
удали

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Model/Apartment.cs
> +    public Guid Id { get; set; }
пусть будет 1 класс entity, от которого будут наследоваться все модели
в классе будет лишь одно поле public guid id 

когда дойдем до написания дбконтекстов удобнее будет наверн

2022-03-29 16:43 UTC, iamquoz commented on src/Simplify.Project.Model/Complex.cs
> +public class Complex
Estate

2022-03-29 16:50 UTC, seljmov commented on src/Simplify.Project.API/Program.cs
> +	public static void Main(string[] args)
Да, но в двух проектах точки старта, если убрать класс и мейн, то будут конфликтовать между собой

2022-03-29 16:50 UTC, seljmov commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +		await Console.Error.WriteLineAsync($"Обращение к эндпоинту {endpoint} привело к ошибке -> {e.Message}");
Асинхронная запись в консоль

2022-03-29 16:51 UTC, seljmov commented on src/Simplify.Project.Front/Shared/NavButton.razor
> +    public string? Classes { get; set; }
Не совсем понял

2022-03-29 16:51 UTC, seljmov commented on src/Simplify.Project.Model/Apartment.cs
> +    public Guid Id { get; set; }
Может лучше интерфейс?

2022-03-29 16:51 UTC, seljmov commented on src/Simplify.Project.Model/Complex.cs
> +public class Complex
?

2022-03-29 16:51 UTC, iamquoz commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +		await Console.Error.WriteLineAsync($"Обращение к эндпоинту {endpoint} привело к ошибке -> {e.Message}");
да, но зачем?

2022-03-29 16:55 UTC, iamquoz commented on src/Simplify.Project.Front/Shared/NavButton.razor
> +    public string? Classes { get; set; }
добавить поле variant, которые будут по типу 
```ts 
primary | secondary | danger | outline | subtle
```

и у кнопки будет n преопределенных классов, каждый из которых соединен с вариантом
считай способ не писать class = "btn btn-primary" везде

2022-03-29 16:56 UTC, iamquoz commented on src/Simplify.Project.API/Program.cs
> +	public static void Main(string[] args)
можно же указать, не?

2022-03-29 16:57 UTC, iamquoz commented on src/Simplify.Project.Model/Apartment.cs
> +    public Guid Id { get; set; }
Да

2022-03-29 16:57 UTC, iamquoz commented on src/Simplify.Project.Model/Complex.cs
> +public class Complex
жилой комплекс с англа - estate

2022-03-29 17:11 UTC, ofu-hub approved these changes, later dismissed

2022-03-29 17:11 UTC, ofu-hub commented on src/Simplify.Project.API/Repositories/IClientRepository.cs
> +    public IEnumerable<Client> GetClients();
Тут разве не должна быть Dto модель?

2022-03-29 17:11 UTC, ofu-hub commented on src/Simplify.Project.API/Repositories/MockClientRepository.cs
> +    private readonly List<Client> _clients;
И тут Dto

2022-03-30 03:29 UTC, seljmov commented on src/Simplify.Project.API/Repositories/IClientRepository.cs
> +    public IEnumerable<Client> GetClients();
Оставил TODO

2022-03-30 03:51 UTC, iamquoz requested changes

2022-03-30 03:51 UTC, iamquoz commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +			return httpResponse.StatusCode == HttpStatusCode.OK
Если в catch не провалились, то не по умолчанию ok?

2022-03-30 03:51 UTC, iamquoz commented on src/Simplify.Project.Front/wwwroot/appsettings.json
> +{
Назови тогда уж appsettings.development.json

2022-03-30 03:51 UTC, iamquoz commented on src/Simplify.Project.Model/Apartment.cs
> +    public Guid Id { get; set; }
Если наследушь, зачем поле гуид тут 🤔

Просто я исходил ещё и из того, чтобы не пришлось начинать каждый класс с guid id, тогда переделать на абстрактный класс, как userbase?

2022-03-30 03:54 UTC, seljmov commented on src/Simplify.Project.Model/Apartment.cs
> +    public Guid Id { get; set; }
Я к тому, что наследуя от абстрактного класса, мы ставим запрет на использование абстрактных классов в будущем, ибо в С# можно только и только от 1 класса наследоваться

2022-03-30 03:56 UTC, seljmov commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +			return httpResponse.StatusCode == HttpStatusCode.OK
В catch проваливается при провальной попытке совершить запрос. Http ответы не являются провалом

2022-03-30 06:07 UTC, iamquoz reviewed
добавляй \n в конце файлов!

2022-03-30 06:07 UTC, iamquoz commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +			return httpResponse.StatusCode == HttpStatusCode.OK
то есть 4xx и 5xx не упадут в catch? 

ладно...

2022-03-30 06:07 UTC, iamquoz commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +		Console.Error.WriteLine($"Обращение к эндпоинту {endpoint} привело к ошибке -> {e.Message}");
Как я понимаю, это потом превратится в логгер?

2022-03-30 06:09 UTC, seljmov commented on src/Simplify.Project.Front/Helpers/HttpClientHelper.cs
> +		Console.Error.WriteLine($"Обращение к эндпоинту {endpoint} привело к ошибке -> {e.Message}");
В консоль будет писать ошибку и стектрейс

2022-03-30 06:31 UTC, neputevshina commented on src/Simplify.Project.API/Repositories/IClientRepository.cs
> +    public IEnumerable<Client> GetClients();
не проще ли использовать list? прямо в интерфейсе

2022-03-30 06:31 UTC, neputevshina commented on src/Simplify.Project.Model/Client.cs
> +    public ICollection<Guid> ApartmentsRelationsIds { get; set; } = new List<Guid>();
public List<Guid> ApartmentsRelationsIds { get; set; } = new();
не могу себе представить, когда тут может понадобиться ienumerable. докажи мне обратное
или это для ef?

2022-03-30 06:34 UTC, iamquoz commented on src/Simplify.Project.API/Repositories/IClientRepository.cs
> +    public IEnumerable<Client> GetClients();
ну enumerable можно в шо угодно кастовать

2022-03-30 09:07 UTC, iamquoz commented on src/Simplify.Project.Model/Client.cs
> +    public ICollection<Guid> ApartmentsRelationsIds { get; set; } = new List<Guid>();
ответил выше

2022-03-30 09:08 UTC, iamquoz approved these changes

2022-03-30 12:08 UTC, merged