Issue 11
SimplifyPlusPlus/simplify-project pull request #22
Opened 2022-05-30 18:53 UTC by seljmov

2022-06-17 19:54 UTC, seljmov commented on src/Simplify.Project.API.Contracts/Apartment/ApartmentBaseDto.cs
> +public class  ApartmentBaseDto
Убрать лишний пробел

2022-06-17 19:55 UTC, seljmov commented on src/Simplify.Project.API.Contracts/Apartment/ApartmentRelationCreateDto.cs
> +using Simplify.Project.Shared;
Возможно, уже не нужно

2022-06-17 19:55 UTC, seljmov commented on src/Simplify.Project.API.Contracts/Apartment/ApartmentRelationRemoveDto.cs
> +namespace Simplify.Project.API.Contracts.Apartment;
Возможно, уже не нужно

2022-06-17 19:56 UTC, seljmov commented on src/Simplify.Project.API.Contracts/Events/EventDataItem.cs
> +namespace Simplify.Project.API.Contracts.Events;
Возможно, уже не нужно

2022-06-17 19:57 UTC, seljmov commented on src/Simplify.Project.API/Controllers/ApartmentController.cs
> +	public async Task<IActionResult> ApartmentRelationCreate([FromBody] ApartmentRelationCreateDto? apartmentRelationCreateDto,
Возможно, методы добавления и удаления связи уже не нужны

2022-06-17 19:59 UTC, seljmov commented on src/Simplify.Project.API/Migrations/20220531171000_AddVirtual.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Можно удалить

2022-06-17 19:59 UTC, seljmov commented on src/Simplify.Project.API/Migrations/20220611045720_EmptyMigration.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Можно удалить

2022-06-17 20:00 UTC, seljmov commented on src/Simplify.Project.Front/Helpers/EventHelper.cs
> +		if (!data.ContainsKey(EventDataKeys.Client))
Удалить

2022-06-18 06:29 UTC, seljmov commented on src/Simplify.Project.API/Repositories/IClientRepository.cs
> +	/// <param name="id">Идентификатор клиента</param>
Убрать строку

2022-06-18 06:30 UTC, seljmov commented on src/Simplify.Project.API/Repositories/MockHouseRepository.cs
> +				// Entrances = new List<Entrance>
Убрать коммент

2022-06-18 06:30 UTC, seljmov commented on src/Simplify.Project.Front/Helpers/EventHelper.cs
> +public static class EventHelper
Документировать

2022-06-18 06:32 UTC, seljmov commented on src/Simplify.Project.Front/Shared/Triangle.razor
> +<style>
Удалить

2022-06-18 06:33 UTC, seljmov commented on src/Simplify.Project.Model/Utils/UserBase.cs
> +
Убрать строку

2022-06-18 06:34 UTC, seljmov commented on src/Simplify.Project.Shared/EventDataKeys.cs
> +public static class EventDataKeys
Документировать

2022-06-18 07:43 UTC, iamquoz requested changes
:trollface:

2022-06-18 07:43 UTC, iamquoz commented on src/Simplify.Project.API.Contracts/Apartment/ApartmentBaseDto.cs
> +namespace Simplify.Project.API.Contracts.Apartment;
я чет сомневаюсь, что нам надо неймспейсы индивидуальные для каждой модели

2022-06-18 07:43 UTC, iamquoz commented on src/Simplify.Project.API.Contracts/Apartment/ApartmentEditDto.cs
> +public class ApartmentEditDto : ApartmentBaseDto
наследуемые dto 😳

2022-06-18 07:43 UTC, iamquoz commented on src/Simplify.Project.Front/Shared/Cards/ApartmentAddExistClientCard.razor.cs
> +	private Action<T> DebounceEvent<T>(Action<T> action, Action callback, TimeSpan interval)
почему тут?

2022-06-18 08:03 UTC, seljmov commented on src/Simplify.Project.API.Contracts/Apartment/ApartmentBaseDto.cs
> +namespace Simplify.Project.API.Contracts.Apartment;
Нужно, иначе будет каша из дто

2022-06-18 08:03 UTC, seljmov commented on src/Simplify.Project.Front/Shared/Cards/ApartmentAddExistClientCard.razor.cs
> +	private Action<T> DebounceEvent<T>(Action<T> action, Action callback, TimeSpan interval)
Поиск среди существующих клиентов

2022-06-18 08:16 UTC, iamquoz commented on src/Simplify.Project.Front/Shared/Cards/ApartmentAddExistClientCard.razor.cs
> +	private Action<T> DebounceEvent<T>(Action<T> action, Action callback, TimeSpan interval)
Зачем код копировать то

2022-06-18 19:24 UTC, iamquoz approved these changes

2022-06-18 19:24 UTC, merged