add dbcontext
SimplifyPlusPlus/simplify-project pull request #6
Opened 2022-04-03 19:43 UTC by iamquoz

Добавлен dbcontext

кроме того, сделан .editorconfig и по всем файлам пройден линтер с этими настройками
немного изменены модели для интеграции с ef

2022-04-03 20:20 UTC, ofu-hub requested changes

2022-04-03 20:20 UTC, ofu-hub commented on src/Simplify.Project.Model/ApartmentRelation.cs
> +	public Apartment Apartment { get; set; } = new();
Почему вместо типа Guid храним саму модель? Как это будет через сервер работать?

2022-04-03 20:37 UTC, neputevshina approved these changes, later dismissed
я ничего не понял :+1:

2022-04-03 20:47 UTC, iamquoz commented on src/Simplify.Project.Model/ApartmentRelation.cs
> +	public Apartment Apartment { get; set; } = new();
в бд хранится ид, мы будем автоматически джойнить квартиру

2022-04-04 05:29 UTC, seljmov commented on src/Simplify.Project.Model/ApartmentRelation.cs
> +	public Apartment Apartment { get; set; } = new();
> Почему вместо типа Guid храним саму модель? Как это будет через сервер работать?

На эту тему долго общались, решили так сделать

2022-04-04 05:36 UTC, seljmov commented on src/Simplify.Project.Model/SimplifyContext.cs
> +public class SimplifyContext : DbContext
Добавь комментарии к классу и полям

2022-04-04 05:37 UTC, seljmov commented on src/Simplify.Project.Model/Simplify.Project.Model.csproj
> +	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.3" />
Перенести контекст, миграции и пакеты в Simplify.Project.API

2022-04-04 05:38 UTC, seljmov commented on src/Simplify.Project.Model/SimplifyContext.cs
> +	public SimplifyContext() { }
Для чего пустой конструктор и нижние 2 метода?

2022-04-04 05:47 UTC, iamquoz commented on src/Simplify.Project.Model/SimplifyContext.cs
> +	public SimplifyContext() { }
Пустой конструктор по докам нужен
Конструктор через base  - тот, который запускается при помощи startup.cs
OnConfiguring для того, чтобы там устанавливать логгеры, настройки миграций и т.д

2022-04-04 05:55 UTC, seljmov commented on src/Simplify.Project.API/Simplify.Project.API.csproj
> +		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.3">
Причем ты тут тоже на ef ссылаешься...

2022-04-04 05:57 UTC, seljmov commented on src/Simplify.Project.API/Repositories/MockClientRepository.cs
> +					new ApartmentRelation {Id = Guid.Parse("00004f64-5717-4562-b3fc-2c963f66afa6") },
Ты зря копировал одно и тоже, тут разные id у всех...

2022-04-04 05:59 UTC, seljmov commented on src/Simplify.Project.Model/SimplifyContext.cs
> +	public SimplifyContext() { }
Которых нет... Пока ничего нет, можно убрать

2022-04-04 06:02 UTC, iamquoz commented on src/Simplify.Project.API/Simplify.Project.API.csproj
> +		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.3">
Там для dotnet ef нужно было...

2022-04-04 06:02 UTC, iamquoz commented on src/Simplify.Project.Model/SimplifyContext.cs
> +	public SimplifyContext() { }
А когда понадобится, заново писать..?

2022-04-04 06:03 UTC, iamquoz commented on src/Simplify.Project.API/Repositories/MockClientRepository.cs
> +					new ApartmentRelation {Id = Guid.Parse("00004f64-5717-4562-b3fc-2c963f66afa6") },
Все равно на бд перешли уже, можно уйти от локальных моков

2022-04-04 07:06 UTC, seljmov commented on src/Simplify.Project.API/Repositories/MockClientRepository.cs
> +					new ApartmentRelation {Id = Guid.Parse("00004f64-5717-4562-b3fc-2c963f66afa6") },
Но ты бы поправил, мок все-таки мок

2022-04-04 07:07 UTC, seljmov commented on src/Simplify.Project.Model/SimplifyContext.cs
> +	public SimplifyContext() { }
Нет, лучше оставить неиспользуемый код, в таком случае и неиспользуемые юзинги будем оставлять, ведь, не засоряет код.

2022-04-04 14:41 UTC, seljmov approved these changes

2022-04-04 14:43 UTC, merged